export const TYPO_MAP: Record<string, string> = {
  detials: 'details',
  detial: 'detail',
  detalis: 'details',
  detaails: 'details',
  detals: 'details',
  profil: 'profile',
  profle: 'profile',
  prafule: 'profile',
  profilee: 'profile',
  salery: 'salary',
  sallery: 'salary',
  salar: 'salary',
  payrol: 'payroll',
  payrole: 'payroll',
  payrolll: 'payroll',
  certifcate: 'certificate',
  certifcates: 'certificates',
  certicate: 'certificate',
  'pay slip': 'payslip',
  'form 16': 'form16',
  'my detaails': 'my details',
  'my profle': 'my profile',
  'my certifcate': 'my certificate',
  cancl: 'cancel',
  cancelr: 'cancel',
  aproove: 'approve',
  approv: 'approve',
  leav: 'leave',
  leafe: 'leave',
  reuest: 'request',
  requst: 'request',
  requist: 'request',
  deteil: 'detail',
  emplyee: 'employee',
  employe: 'employee',
  employeess: 'employees',
  holidayes: 'holidays',
  balnce: 'balance',
  balence: 'balance',
  balanc: 'balance',
  salry: 'salary',
  slary: 'salary',
  payslp: 'payslip',
  payslipp: 'payslip',
  paislip: 'payslip',
  hloiday: 'holiday',
  holidey: 'holiday',
  holday: 'holiday',
  holliday: 'holiday',
  cancle: 'cancel',
  cancell: 'cancel',
  aply: 'apply',
  appply: 'apply',
  aplly: 'apply',
  annoucement: 'announcement',
  announcment: 'announcement',
  anouncement: 'announcement',
  polcy: 'policy',
  policey: 'policy',
  polisy: 'policy',
  casul: 'casual',
  casuaal: 'casual',
  sik: 'sick',
  sck: 'sick',
};